{
  "timestamp": "2025-09-14T20:02:31.482207",
  "tests_run": 23,
  "failures": 1,
  "errors": 0,
  "skipped": 5,
  "success_rate": 95.65217391304348,
  "details": {
    "failures": [
      "(<__main__.TestIntegrationPoints testMethod=test_pandas_imports>, 'Traceback (most recent call last):\\n  File \"/Users/matheusferreira/Documents/Pessoal/Faculdade/2025-2/tcc/tcc_bird-identify/test_unit.py\", line 361, in test_pandas_imports\\n    self.assertTrue(hasattr(pd, func), f\"Função {func} não encontrada no Pandas\")\\nAssertionError: False is not true : Função to_csv não encontrada no Pandas\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \"/Users/matheusferreira/Documents/Pessoal/Faculdade/2025-2/tcc/tcc_bird-identify/test_unit.py\", line 365, in test_pandas_imports\\n    self.fail(f\"Erro ao importar Pandas: {e}\")\\nAssertionError: Erro ao importar Pandas: False is not true : Função to_csv não encontrada no Pandas\\n')"
    ],
    "errors": []
  }
}